config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :basic_heroscopes

  root 'basic_heroscopes#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/basic_heroscope.rb
require 'net/http'
require 'uri'

class BasicHeroscope < ActiveRecord::Base
	validates_presence_of :name, :time, :birth_place, :date
	belongs_to :user
	@@baseURL = "http://api.vedicrishiastro.com/v1/"

	before_save :determine_lat_and_long, :get_basic_heroscope_details


	def change
		self.update_attributes(name: "Aishu weds Shivu")
	end

	private

	def determine_lat_and_long
		results = Geocoder.search(self.birth_place)
		results.first.coordinates[0]
		self.lat = results.first.coordinates[0]
		self.lon = results.first.coordinates[1]
	end

	def get_basic_heroscope_details
		
		userID = "602816"
		apiKey = "e10e6338e687949cc20f8a2ab4938860"

		data = {
			'day' => self.date.day,
			'month' => self.date.month,
			'year' => self.date.year,
			'hour' => self.time.hour,
			'min' => self.time.min,
			'lat' => self.lat,
			'lon' => self.lon,
			'tzone' => self.tzone
		}
		resource = "astro_details"
		url = URI.parse(@@baseURL+ resource)
	    req = Net::HTTP::Post.new(url)
	    req.basic_auth userID, apiKey
	    req.set_form_data(data)
	    resp = Net::HTTP.new(url.host, url.port).start {|http| http.request(req) }
		result = JSON.parse(resp.body)
		
		self.ascendant = result["ascendant"]
    	self.varna = result["Varna"] 
    	self.vashya = result["Vashya"]
    	self.yoni = result["Yoni"]
    	self.gana = result["Gan"]
    	self.nadi = result["Nadi"]
    	self.rashi_adipathi = result["SignLord"]
    	self.rashi = result["sign"]
    	self.nakshtra = result["Naksahtra"]
    	self.nakshtra_adipathi = result["NaksahtraLord"]
    	self.charan = result["Charan"]
    	self.yog = result["Yog"]
    	self.karan = result["Karan"]
    	self.tithi = result["Tithi"]
    	self.yunja = result["yunja"]
    	self.tatva = result["tatva"]
    	self.name_alphabet =  result["name_alphabet"]
    	self.paya = result["paya"]
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :basic_heroscopes

   validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/basic_heroscopes_controller.rb
class BasicHeroscopesController < ApplicationController
  before_action :set_basic_heroscope, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :show, :edit, :update, :destroy]
  # GET /basic_heroscopes
  # GET /basic_heroscopes.json
  def index
    @basic_heroscopes = BasicHeroscope.all
    @basic_heroscope = BasicHeroscope.new
  end

  # GET /basic_heroscopes/1
  # GET /basic_heroscopes/1.json
  def show
  end

  # GET /basic_heroscopes/new
  def new
    @basic_heroscope = BasicHeroscope.new
  end

  # GET /basic_heroscopes/1/edit
  def edit
  end

  # POST /basic_heroscopes
  # POST /basic_heroscopes.json
  def create
    @basic_heroscope = BasicHeroscope.new(basic_heroscope_params)
    @basic_heroscope.user_id = current_user.id
    @basic_heroscope.tzone = 5.5
    respond_to do |format|
      if @basic_heroscope.save
        format.html { redirect_to @basic_heroscope, notice: 'Basic heroscope was successfully created.' }
        format.json { render :show, status: :created, location: @basic_heroscope }
      else
        format.html { render :new }
        format.json { render json: @basic_heroscope.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /basic_heroscopes/1
  # PATCH/PUT /basic_heroscopes/1.json
  def update
    respond_to do |format|
      if @basic_heroscope.update(basic_heroscope_params)
        format.html { redirect_to @basic_heroscope, notice: 'Basic heroscope was successfully updated.' }
        format.json { render :show, status: :ok, location: @basic_heroscope }
      else
        format.html { render :edit }
        format.json { render json: @basic_heroscope.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basic_heroscopes/1
  # DELETE /basic_heroscopes/1.json
  def destroy
    @basic_heroscope.destroy
    respond_to do |format|
      format.html { redirect_to basic_heroscopes_url, notice: 'Basic heroscope was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basic_heroscope
      @basic_heroscope = BasicHeroscope.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basic_heroscope_params
      params.require(:basic_heroscope).permit(:name, :date,:time , :lat, :lon, :tzone, :ascendant, :varna, :vashya, :yoni, :gana, :nadi, :rashi_adipathi, :rashi, :nakshtra, :nakshtra_adipathi, :charan, :yog, :karan, :tithi, :yunja, :tatva, :name_alphabet, :paya, :birth_place, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_heroscopes_helper.rb
module BasicHeroscopesHelper
end

app/views/basic_heroscopes/_form.html.erb
<%= form_for(@basic_heroscope) do |f| %>
  <% if @basic_heroscope.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basic_heroscope.errors.count, "error") %> prohibited this basic_heroscope from being saved:</h2>

      <ul>
      <% @basic_heroscope.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.date_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :time %><br>
    <%= f.time_select :time, class: "form-control" %>
  </div>

   <div class="form-group">
    <%= f.label :birth_place, "Give birth place Taluk Name" %><br>
    <%= f.text_field :birth_place, class: "form-control" %>
  </div>
  <div class="actions">
    <center><%= f.submit "Get Details", class: "btn btn-primary" %></center>
  </div>
<% end %>

app/views/basic_heroscopes/edit.html.erb
<h1>Editing Basic Heroscope</h1>

<%= render 'form' %>

<%= link_to 'Show', @basic_heroscope %> |
<%= link_to 'Back', basic_heroscopes_path %>

app/views/basic_heroscopes/index.html.erb
<center>
  <h3 class="well"  style="background-color: #5499C7;">Listing of Your Basic Heroscope Documents</h3>
</center>
  <%if not user_signed_in?%>
    <marquee style="color: rgb(0,0,255); font-size: 20px;     font-family: Times New Roman">
      Please Register to get your Heroscope details.
    </marquee>
  <% elsif current_user.basic_heroscopes.present? %>
    <marquee style="color: rgb(0,0,255); font-size: 20px;">
      Type something in the input field to search reports, You can get basic heroscope details and numerology details.
    </marquee>
    <div>
      <center>
        <input class="form-control" id="myInput" type="text" placeholder="Search by Name, Time, Place" style="width: 450px;">
      </center>
    </div>
  <% else %>

  <% end %>

<% if user_signed_in? and current_user.basic_heroscopes.present? %>
<br/>
  <div class="col-md-12">
  <table class="table table-hover">
    <thead style="background-color:#F8C471">
      <tr>
        <th><center>Name</center></th>
        <th><center>Birth Date</center></th>
        <th><center>Birth Time</center></th>
        <th><center>Birth Place</center></th> 
        <th><center>Get Full Details</center></th>
        </tr>
    </thead>
    <tbody id="myTable">
      <% @basic_heroscopes.each do |basic_heroscope| %>
        <tr>
          <% if basic_heroscope.user_id == current_user.id %>
          <td><center><%= basic_heroscope.name%></center></td>
          <td><center><%= basic_heroscope.date%></center></td>
          <td>
            <center>
              <% if basic_heroscope.time.hour > 12 %>
                <%= basic_heroscope.time.hour - 12%> 
              <%else%>
                <%= basic_heroscope.time.hour%> 
              <% end %>
              : <%= basic_heroscope.time.min %>
              <%if basic_heroscope.time.hour > 12 %>
                : PM
              <%else%>
                : AM
              <% end %>
            </center>
          </td>
          <td><center><%= basic_heroscope.birth_place.capitalize%></center></td>
          <td><center><%= link_to "View", basic_heroscope, class: "btn btn-success"%></center></td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
<% end %>
<br/>
<br/>
<br/>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<center>
  <% if user_signed_in? %>
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Get Your Heroscope</button>
  <% end %>
</center>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Please fill the below details</h4>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>


<div class="col-md-3"></div>
<div class="col-md-6">
<%if not user_signed_in?%>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="1.jpg" alt="Los Angeles" style="width: 539px; height: 300px;">
    </div>

    <div class="item">
      <img src="2.jpg" alt="Chicago" style="width: 539px; height: 300px;">
    </div>

    <div class="item">
      <img src="3.jpg" alt="New York" style="width: 539px; height: 300px;">
    </div>

    <div class="item">
      <img src="4.jpg" alt="New York" style="width: 539px; height: 300px;">
    </div>

    <div class="item">
      <img src="5.jpg" alt="New York" style="width: 539px; height: 300px;">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<% end %>
</div>

app/views/basic_heroscopes/new.html.erb
<h1>New Basic Heroscope</h1>

<%= render 'form' %>

<%= link_to 'Back', basic_heroscopes_path %>

app/views/basic_heroscopes/show.html.erb
<div class="container"> 
  <div class="row">
    <div class="col-md-12 jumbotron" style="color: #F4D03F; background-color: #1E88E5;">
      <center><b style="font-size: 40px;">Basic Heroscope Details of <%= @basic_heroscope.name.upcase%></b></center>
    </div>
    <div style=" padding-top:10px;height:50px;color: #1B2631; background-color: #1E88E5; font-size: 20px;" class="col-md-12 well">
      <b class="col-md-4">Birth Place : <%= @basic_heroscope.birth_place.capitalize%> </b>

      <b class="col-md-4">Birth Date : <%= @basic_heroscope.date%> </b>

      <b class="col-md-4">Birth Time : <% if @basic_heroscope.time.hour > 12 %>
         <%= @basic_heroscope.time.hour - 12%> 
        <%else%>
          <%= @basic_heroscope.time.hour%> 
        <% end %>

        : <%= @basic_heroscope.time.min %>
        <%if @basic_heroscope.time.hour > 12 %>
          : PM
        <%else%>
          : AM
        <% end %>
         </b>
    </div>  
    <div class="col-sm-4" style="font-size: 20px;" >
      <div class="panel panel-primary">
        <div class="panel-body">
          Birth Name Alphabet : <i style="float: right"><%= @basic_heroscope.name_alphabet%></i><br/> 
          Nakshtra : <i style="float: right"><%= @basic_heroscope.nakshtra %></i><br/>
          Charan : <i style="float: right"><%= @basic_heroscope.charan %></i> <br/>
          Rashi : <i style="float: right"><%= @basic_heroscope.rashi %></i> <br/>
          Nakshtra adipati : <i style="float: right"><%= @basic_heroscope.nakshtra_adipathi %></i> <br/>
          Rashi adipati : <i style="float: right"><%= @basic_heroscope.rashi_adipathi %></i> <br/>
        </div>
      </div>
    </div>

    <div class="col-sm-4" style="font-size: 20px;">
      <div class="panel panel-primary">
        <div class="panel-body">
         Paksha and  Tithi : <i style="float: right"><%= @basic_heroscope.tithi %></i> <br/>
          Yog : <i style="float: right"><%= @basic_heroscope.yog %></i> <br/>
          Karan : <i style="float: right"><%= @basic_heroscope.karan %></i> <br/>
          Nadi : <i style="float: right"><%= @basic_heroscope.nadi %></i> <br/>
          Yoni : <i style="float: right"><%= @basic_heroscope.yoni %></i> <br/>
          Gana : <i style="float: right"><%= @basic_heroscope.gana %></i> <br/>
        </div>
      </div>
    </div>

    <div class="col-sm-4" style="font-size: 20px;">
      <div class="panel panel-primary">
        <div class="panel-body">
          Varna : <i style="float: right"><%= @basic_heroscope.varna %></i> <br/>
          Vashya : <i style="float: right"><%= @basic_heroscope.vashya %></i> <br/>
          Ascendant : <i style="float: right"><%= @basic_heroscope.ascendant %></i> <br/>
          Yunja : <i style="float: right"><%= @basic_heroscope.yunja %></i> <br/>
          Tatva : <i style="float: right"><%= @basic_heroscope.tatva %></i> <br/>
          Paya : <i style="float: right"><%= @basic_heroscope.paya %></i> <br/>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <center><%= link_to "HOME", basic_heroscopes_path, class: "btn btn-warning"%></center>      
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Askmonk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<script src = "//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js "></script>

</head>
	<body style="font-family: Times New Roman">
		<div class="container">
			<nav class="navbar navbar-inverse">
		  		<div class="container-fluid">
		    		<div class="navbar-header">
		      			<a class="navbar-brand"  href="/basic_heroscopes">ASKMONK</a>
		    		</div>
		    		<ul style="font-size: 20px;" class="nav navbar-nav navbar-right">
		    			<% if not user_signed_in? %>
		      			<li><a data-method="get" href="/askmonk/login">Admin</a></li>
		      			<li>
		      				<%= link_to new_user_registration_path do %>
		      					<span class="glyphicon glyphicon-user"></span>
		      				<% end %>
		      			</li>
		      			<li>
		      				<%= link_to new_user_session_path do %>
		      					<span class="glyphicon glyphicon-log-in"></span>
		      				<% end %>
		      			</li>
		      				
		      			<% else %>
		      				<li><%= link_to askmonk_root_path do %>
		      						<span class="glyphicon glyphicon-home"></span>
		      					<% end %>
		      				</li>
							<li><%= link_to destroy_user_session_path, method: :delete do %>
									<span class="glyphicon glyphicon-off"></span>
								<% end %>
							</li>
		      			<% end %>
		    		</ul>
		  		</div>
			</nav>
		</div>	
		<div class="container" style="font-family: Times New Roman;">
			<%= yield %>
		</div>
		<br/><br/>
		<footer style="font-family: Times New Roman; height: 50px; background-color: #95A5A6;" class="container page-footer font-small blue pt-4">
			<div sytle="backgorund-color: red" class="container-fluid text-left text-md-left"><br/>
				<div class="footer-copyright text-left py-3">© 2018 Copyright:
	      			<a href="#"> www.askmonk.com</a> <b style="float: right;">Contact Us : +91 9731937369, Email: mail4hiremath@gmail.com </b>
	    		</div>

			</div>
		</footer>
	</body>
</html>
<br/>